name: Mark stale issues

on:
  schedule:
    - cron: '15 5 * * *'

jobs:
  stale-issues:

    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - uses: actions/stale@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'issue inativa'
          stale-issue-label: 'no-issue-activity'
          days-before-stale: 7

